#!/bin/bash
set -x
export root=`dirname $0`

source $root/job/job.sh


PROJECT=
PLATFORM=
REFSPEC=
ID=

while [ $# -gt 0 ]; do
    opt=$1
    shift
    case "$opt" in
        azazie|zzcms|loveprom|admkt|feed|newsletter|editor|erp|shield|mps|romeo) 
            PROJECT=$opt       
            ;;
        prod|pre|test)  
            PLATFORM=$opt        
            ;;
        feature/*|develop|release/*|ptest*)
            REFSPEC=$opt
            ;;
        0|1|2|3|4|5|6|7|8|9)
            ID=$opt
            ;;
        *)
            echo "Usage $0 [azazie|zzcms|loveprom|feed|newsletter|editor|erp|shell|mps|romeo] [prod|pre|test] refspec [ID]"
            exit 1
            ;;
    esac
done

# mac
PROJECT=`echo "$PROJECT" | cut -c 1-1 | tr 'a-z' 'A-Z'``echo "$PROJECT" | cut -c 2-`
PLATFORM=`echo "$PLATFORM" | cut -c 1-1 | tr 'a-z' 'A-Z'``echo "$PLATFORM" | cut -c 2-`
job=Build${PROJECT}${PLATFORM}
# linux
# job=Build${PROJECT^}${PLATFORM^}

`$job $REFSPEC $ID`
